/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RecipesImport } from './routes/recipes'
import { Route as RecentlyAddedImport } from './routes/recently-added'
import { Route as MostCookedImport } from './routes/most-cooked'
import { Route as LongTimeImport } from './routes/long-time'
import { Route as AddRecipeImport } from './routes/add-recipe'
import { Route as IndexImport } from './routes/index'
import { Route as RecipeRecipeIdNameImport } from './routes/recipe.$recipeIdName'
import { Route as CategoryCategoryNameImport } from './routes/category.$categoryName'

// Create/Update Routes

const RecipesRoute = RecipesImport.update({
  path: '/recipes',
  getParentRoute: () => rootRoute,
} as any)

const RecentlyAddedRoute = RecentlyAddedImport.update({
  path: '/recently-added',
  getParentRoute: () => rootRoute,
} as any)

const MostCookedRoute = MostCookedImport.update({
  path: '/most-cooked',
  getParentRoute: () => rootRoute,
} as any)

const LongTimeRoute = LongTimeImport.update({
  path: '/long-time',
  getParentRoute: () => rootRoute,
} as any)

const AddRecipeRoute = AddRecipeImport.update({
  path: '/add-recipe',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipeRecipeIdNameRoute = RecipeRecipeIdNameImport.update({
  path: '/recipe/$recipeIdName',
  getParentRoute: () => rootRoute,
} as any)

const CategoryCategoryNameRoute = CategoryCategoryNameImport.update({
  path: '/category/$categoryName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/add-recipe': {
      preLoaderRoute: typeof AddRecipeImport
      parentRoute: typeof rootRoute
    }
    '/long-time': {
      preLoaderRoute: typeof LongTimeImport
      parentRoute: typeof rootRoute
    }
    '/most-cooked': {
      preLoaderRoute: typeof MostCookedImport
      parentRoute: typeof rootRoute
    }
    '/recently-added': {
      preLoaderRoute: typeof RecentlyAddedImport
      parentRoute: typeof rootRoute
    }
    '/recipes': {
      preLoaderRoute: typeof RecipesImport
      parentRoute: typeof rootRoute
    }
    '/category/$categoryName': {
      preLoaderRoute: typeof CategoryCategoryNameImport
      parentRoute: typeof rootRoute
    }
    '/recipe/$recipeIdName': {
      preLoaderRoute: typeof RecipeRecipeIdNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AddRecipeRoute,
  LongTimeRoute,
  MostCookedRoute,
  RecentlyAddedRoute,
  RecipesRoute,
  CategoryCategoryNameRoute,
  RecipeRecipeIdNameRoute,
])

/* prettier-ignore-end */
